### ISSUE TITLE
Opt-Out-Cookie nutzbar machen

### ISSUE THREAD

**Issue by elricco** [FriendsOfREDAXO/analytics#10]
Inzwischen benötigt man nicht mehr unbedingt das OptOut-Addon welches von Google bereitgestellt wird. Die ga.js und analytics.js wurden um einen setzbaren Parameter erweitert. Dieser kann auch als sogenanntes Opt-Out-Cookie gesetzt werden z.B. durch einen Link in der Datenschutzerklärung der Webseite.

**Comment by elricco** [comment]
Hier noch der Code / das Beispiel dazu: https://developers.google.com/analytics/devguides/collection/gajs/#example bzw. die Kurzform dazu, dass es ebenfalls fürs analytics.js gilt: https://developers.google.com/analytics/devguides/collection/analyticsjs/user-opt-out#opt-out_of_tracking_for_your_site

**Comment by phoebusryan** [comment]
Ich hab es mal gemerged und veröffentlicht in Version 1.2.0. Kannst du es mal testen?

**Comment by elricco** [comment]
Werde ich gleich mal in meinem playground machen.
