### ISSUE TITLE
"Klassisches Analytics" nutzbar machen

### ISSUE THREAD

**Issue by elricco** [FriendsOfREDAXO/analytics#12]
Auch wenn es heutzutage nicht mehr vorkommen sollte, es gibt doch User, die immer noch die alte Version in ihre Webseite eingebunden haben und dies auch nicht ändern wollen. Um die Einbindung für den Developer / Webmaster einfacher zu gestalten, wird auch das alte Script berücksichtigt.

**Comment by phoebusryan** [comment]
> Auch wenn es heutzutage nicht mehr vorkommen sollte

 ... das ist doch genau der Punkt. Google wird die alte Version ohnehin bald abschiessen. Es ist deshalb fraglich ob der Einbau davon Sinn macht.

> und dies auch nicht ändern wollen

Hast du hierfür ein konkretes Argument? Grundsätzlich wird bei neuen Webseiten logischerweise der neue Code eingebaut. Kein Mensch geht alte Seiten durch und ersetzt sein GA-Code durch dieses Addon, will aber trotzdem den alten Code haben. Oder übersehe ich hier was?

**Comment by elricco** [comment]
Ich hab es eingebaut, weil ich gerade aktuell bei einem Kunden den konkreten Fall habe. Die nutzen immer noch die alte Version - haben uns den zum Einbau in die Microsite geschickt und der MUSS auch bitte genau so eingebaut werden.

Ich persönlich finde das auch nicht toll, aber bis es offiziell nicht mehr komplett unterstützt wird, dachte ich es wäre ein "Nice-to-have". Tolles Argument 😅
