### ISSUE TITLE
Ausgabe leer

### ISSUE THREAD

**Issue by bega011** [FriendsOfREDAXO/analytics#16]
Die Ausgabe funktioniert nicht. An der Stelle im Template (echo rex_analytics::output(true);) wird nichts ausgegeben obwohl die ID eingetragen ist.

**Comment by phoebusryan** [comment]
Die Ausgabe ist leer, wenn du im Backend eingeloggt bist.. einfach damit Analytics die eigenen Aufrufe nicht mit trackt. Liegt es daran?

**Comment by bega011** [comment]
Genau. Habs gerade getestet wenn im Backend nicht eingeloggt, hats geklappt, also funktioniert hervorragend. Vielleicht sollte man das in der Hilfe-Datei noch explizit reinschreiben, damit es offensichtlich wird. 
Ansonsten eine feine Sache, danke ;)

**Comment by phoebusryan** [comment]
Stimmt, ich kann es noch in die Hilfe reinnehmen.
