### ISSUE TITLE
Google TagManager

### ISSUE THREAD

**Issue by marcohanke** [FriendsOfREDAXO/analytics#18]
Moin @schuer, kennst du / nutzt du den Google Tag Manager?
Das wäre doch eigentlich interessanter als eine reine Analytics integration, wobei der ja schon ein Teil deiner Arbeit übernimmt. Ändert sich der AnalyticsCode, brauchst du nichts anpassen, das macht der TagManager.

**Comment by phoebusryan** [comment]
Warum taggst du da @schuer? Das Addon ist von mir ;)

**Comment by marcohanke** [comment]
@schuer ist doch König FOR oder? ;-) Spaß beiseite, ich hab mit Github so gut wie nix am Hut. Wenn du auf der Startseite des Repos bist, grinst dich Schuer an, aber nur weil er zuletzt was comittet hat. Hab ich jetzt auch kapiert. mea culpa @phoebusryan

**Comment by schuer** [comment]
Hehe, ich halte mich raus ;)
Aber ja, Tag Manager wäre nice!

**Comment by phoebusryan** [comment]
Tag Manager ist sicher nice und grundsätzliche eine sinnvolle Ergänzung (und/oder ein eigenes Addon wert?) ... jedenfalls habe ich bisher immer nur Analytics genutzt und mir fehlt deshalb das nötige TagManager-Wissen.

**Comment by marcohanke** [comment]
@phoebusryan Im Prinzip ist das ganz simple. Du erstellst einen Container im Tagmanager. Den Code bindest du dann statt dem Analyticscode im Code ein und fertig.
Alles weitere läuft über den Tag Manager. Möchtest du Google Analytics nutzen, erstellst du einen Analytics-Tag klickst auf aktualisieren und fertig ist die Laube. Hast du ein anderes Analyticskonto bleibt der Code auf deiner Homepage unangetastet. Es findet spielt sich alles innerhalb des Containers im TagManager ab. Wobei sich die Frage stellt, für was man dann noch ein Addon braucht...

**Comment by schuer** [comment]
> Wobei sich die Frage stellt, für was man dann noch ein Addon braucht...

Um ein paar relevante Kennzahlen — als schlichtes schickes Diagramm aufbereitet — im REDAXO-Backend darzustellen. Für alle Redakteure, die die notwendigen Rechte dafür haben.

(Das wäre zumindest meine Anforderung an so ein Addon.)

**Comment by marcohanke** [comment]
Dann wird's mit dem Tag Manager vermutlich wieder etwas komplexer. Grundsätzlich wäre das aber schon geil, wenn mein Kunde einfach die Besucherzahlen und Sitzungsdauer der letzten Monate sehen würde. Top Idee!

**Comment by phoebusryan** [comment]
Ich habe gestern für eine Webseite einen Analytics-Code generieren wollen, habe aber automatisch einen GTM-Code bekommen. Gibts den klassischen Analytics-Code nicht mehr?

**Comment by marcohanke** [comment]
Wo hast du den denn generieren lassen? GTM kann Analytics nicht ersetzen. GTM ist nur der Container, den AnalyticsCode musst du trotzdem generieren lassen, auch wenn du GTM nutzt.

**Comment by phoebusryan** [comment]
nach der anleitung hier:
https://support.google.com/analytics/answer/1042508?hl=de

**Comment by marcohanke** [comment]
Also ich kann mir nach wie vor meinen TrackingCode für die einzelnen Propertys anzeigen lassen.
Was etwas verwirrend ist, ist das das Script auf googletagmanager.com liegt (war früher nicht so).
Aber trotzdem kannst du den Code doch einfach in den Head packen ???

**Comment by phoebusryan** [comment]
Hm ja, ich bekomme einfach sowas:

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-XXXXXX"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-XXXXXXX');
</script>
```

**Comment by marcohanke** [comment]
Und der funktioniert nicht im Head oder wo ist Problem.

**Comment by phoebusryan** [comment]
doch, aber er ist inkompatibel mit dem addon aktuell. müsste es einfach updaten

**Comment by marcohanke** [comment]
Achsooooo ;-)
ja das musst du vermutlich aktualisieren.
Google ändert da irgendwie immer mal was. Deshalb hab ich irgendwann den Tagmanager genutzt, den juckt das nicht so.
Ist dafür aber wieder mehr Aufwand mit Tag erstellen, Tag veröffentlichen, kommt am Ende vermutlich auf das selbe raus solange du „nur“ Analytics nutzt.

**Comment by phoebusryan** [comment]
Ja.. scheint mir keinen Unterschied zu machen. Ich schliesse deshalb hier.
