### ISSUE TITLE
Zwei Rechte für eine Seite

### ISSUE THREAD

**Issue by DanielWeitenauer** [FriendsOfREDAXO/analytics#19]
Hi, so wie es aussieht hat Analytics zwei Nutzer-Rechte, die beide für eine Rolle aktiviert werden müssen, um Zugriff auf die Konfigurationsseite zu erhalten. Könnte man die beiden nicht kombinieren?

**Comment by phoebusryan** [comment]
Das ist eigentlich standard. Eine um das Addon zu sehen und eine für jede Unterseite. Das macht es flexibel.

**Comment by DanielWeitenauer** [comment]
> Das macht es flexibel.
Das hatte ich mir fast schon gedacht. Es könnte helfen, die beiden Rechte als zusammengehörend erkennbar zu machen. Durch die Übersetzung stehen sie nicht immer untereinander. Ich habe mal einen Übersetzungsvorschlag mit dem Addon-Namen vorne gemacht. Vielleicht magst du den übernehmen: #20

**Comment by phoebusryan** [comment]
Danke; ein gutes Argument. Grundsätzlich sollte man das bei all meinen Addon machen... :-|
