### ISSUE TITLE
analytics gibt nichts mehr aus

### ISSUE THREAD

**Issue by darwin26** [FriendsOfREDAXO/analytics#25]
HI,
bin mir noch nicht sicher an was es liegt... aber via
`echo analytics::output(true);`
wirft es mir leider nichts mehr aus. UA (Tracking-ID) ist im AddOn hinterlegt.
IP anonymisieren : deaktiviert
Opt-Out-Cookie setzbar machen: deaktiviert
(egal ob ich auchs aktibiere, kommt nichts bzw, wird im Quelltext nichts ausgegeben (leer)

*strange*

**Comment by phoebusryan** [comment]
Bist du eingeloggt im Backend? Wenn ja, ist es deaktiviert :)

**Comment by darwin26** [comment]
*grmpf*.
danke, das wars ;) ...

**Comment by dpf-dd** [comment]
Hatte soeben das gleiche Problem als "Neu-User". Da im readme von diesem Verhalten nichts steht, war ich schon kurz davor ein Issue hier zu öffnen - bis ich das las...

Evtl. wäre ja ein Hinweis in der readme sinnvoll, dass man da nicht gleich flucht wenn nach dem installen des AddOns nix passiert... (weil ich mich normal nicht auslogge zum Testen...)

Ansonste... feine Sache das Addon.
Gruß
Stefan
