### ISSUE TITLE
Code wird nicht erzeugt

### ISSUE THREAD

**Issue by erraiva** [FriendsOfREDAXO/analytics#27]
Hallo, die Platzierung des PHP-Schnipsels hat keine Auswirkung. Es wird kein Code erzeugt.
Könnt ihr mal prüfen? Danke :-)

Redaxo 5.6.2

**Comment by phoebusryan** [comment]
Klassiker. Der Code ist nur sichtbar, wenn du im Backend NICHT eingeloggt bist, damit die Statistik nicht verfälscht wird.

**Comment by erraiva** [comment]
Ja, so war's :-) Danke!
