### ISSUE TITLE
IP anonymisieren

### ISSUE THREAD

**Issue by elricco** [FriendsOfREDAXO/analytics#9]
Sollte optional anwählbar sein. Damit man nicht von Hand am Fragment rumbasteln muss. Da dies inzwischen ja auf den meisten (deutschen) Webseiten Pflicht ist, um Google Analytics datenschutzkonform einsetzen zu können.

**Comment by phoebusryan** [comment]
Da waren noch ein paar Fehler drin. Ich habe sie nun aber gefixt und den Code gemerged
